In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
sample1 = pd.read_json('json/sample_1.json', lines=True)

In [3]:
sample1.head(5)

,_id,contributors,coordinates,created_at,entities,extended_entities,favorite_count,favorited,filter_level,geo,...,quoted_status,quoted_status_id,quoted_status_id_str,retweet_count,retweeted,source,text,timestamp_ms,truncated,user
0,{'$oid': '571013410a1776314079ac76'},NaN,None,2016-04-14 22:01:27,"{'symbols': [], 'user_mentions': [{'indices': ...",NaN,0,False,low,None,...,NaN,NaN,NaN,0,False,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",Mitico Mirco ! #peaceandlove #gazebo @welikech...,2016-04-14 22:01:27.836,False,"{'follow_request_sent': None, 'profile_use_bac..."
1,{'$oid': '571013430a1776314079ac77'},NaN,None,2016-04-14 22:01:37,"{'symbols': [], 'user_mentions': [], 'hashtags...",NaN,0,False,low,None,...,"{'contributors': None, 'truncated': False, 'te...",{'$numberLong': '720732885691600896'},7.207329e+17,0,False,"<a href=""http://twitter.com/download/android"" ...",J ai pas regard√© mais une question me taraude ...,2016-04-14 22:01:37.142,False,"{'follow_request_sent': None, 'profile_use_bac..."
2,{'$oid': '5710135c0a1776314079ac7a'},NaN,None,2016-04-14 22:01:58,"{'symbols': [], 'user_mentions': [{'indices': ...",NaN,0,False,low,None,...,NaN,NaN,NaN,0,False,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",@amadore_a @didi1711_ @eddyxe1qeg @pacorodrigu...,2016-04-14 22:01:58.194,False,"{'follow_request_sent': None, 'profile_use_bac..."
3,{'$oid': '571013850a1776314079ac81'},NaN,None,2016-04-14 22:02:44,"{'symbols': [], 'user_mentions': [{'indices': ...",NaN,0,False,low,None,...,NaN,NaN,NaN,0,False,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",@latif600 \n\nÿ≤ÿßÿØ ÿßŸÑŸÑŸá ŸÜŸàÿ±ŸÉ üíê ..,2016-04-14 22:02:44.199,False,"{'follow_request_sent': None, 'profile_use_bac..."
4,{'$oid': '571013900a1776314079ac84'},NaN,None,2016-04-14 22:02:46,"{'symbols': [], 'user_mentions': [{'indices': ...",NaN,0,False,low,None,...,NaN,NaN,NaN,0,False,"<a href=""http://twitter.com/download/iphone"" r...","@PabloRicon es que es la polla , solo el sitio...",2016-04-14 22:02:46.280,False,"{'follow_request_sent': None, 'profile_use_bac..."

In [4]:
sample2 = pd.read_json('json/sample_2.json', lines=True)

In [5]:
sample2.head(5)

,_id,contributors,coordinates,created_at,entities,extended_entities,favorite_count,favorited,filter_level,geo,...,quoted_status,quoted_status_id,quoted_status_id_str,retweet_count,retweeted,source,text,timestamp_ms,truncated,user
0,{'$oid': '5710131a0a1776314079ac6a'},NaN,"{'type': 'Point', 'coordinates': [8.49031772, ...",2016-04-14 22:00:44,"{'symbols': [], 'user_mentions': [], 'hashtags...",NaN,0,False,low,"{'type': 'Point', 'coordinates': [47.39970386,...",...,NaN,NaN,NaN,0,False,"<a href=""http://instagram.com"" rel=""nofollow"">...",üá®üá≠ @ Limmat https://t.co/9w6zcuE6B8,2016-04-14 22:00:44.462,False,"{'follow_request_sent': None, 'profile_use_bac..."
1,{'$oid': '571013850a1776314079ac81'},NaN,None,2016-04-14 22:02:44,"{'symbols': [], 'user_mentions': [{'indices': ...",NaN,0,False,low,None,...,NaN,NaN,NaN,0,False,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",@latif600 \n\nÿ≤ÿßÿØ ÿßŸÑŸÑŸá ŸÜŸàÿ±ŸÉ üíê ..,2016-04-14 22:02:44.199,False,"{'follow_request_sent': None, 'profile_use_bac..."
2,{'$oid': '571013a70a1776314079ac87'},NaN,"{'type': 'Point', 'coordinates': [6.91973956, ...",2016-04-14 22:03:04,"{'symbols': [], 'user_mentions': [], 'hashtags...",NaN,0,False,low,"{'type': 'Point', 'coordinates': [46.42912905,...",...,NaN,NaN,NaN,0,False,"<a href=""http://instagram.com"" rel=""nofollow"">...",Throwback to strollin around Geneva lake alone...,2016-04-14 22:03:04.757,False,"{'follow_request_sent': None, 'profile_use_bac..."
3,{'$oid': '5710140b0a1776314079ac94'},NaN,None,2016-04-14 22:04:59,"{'symbols': [], 'user_mentions': [], 'hashtags...",NaN,0,False,low,None,...,NaN,NaN,NaN,0,False,"<a href=""http://twitter.com/download/iphone"" r...",NO ES POSSIBLE,2016-04-14 22:04:59.384,False,"{'follow_request_sent': None, 'profile_use_bac..."
4,{'$oid': '571014220a1776314079ac99'},NaN,None,2016-04-14 22:05:20,"{'symbols': [], 'user_mentions': [{'indices': ...",NaN,0,False,low,None,...,NaN,NaN,NaN,0,False,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",COPIEM E COLEM OS TWEETS DA @ConexaoMixer PEDI...,2016-04-14 22:05:20.893,False,"{'follow_request_sent': None, 'profile_use_bac..."

# Analysis of data from 2016

## Total number of Tweets

In [6]:
print('Total number of status updates for sample 1:', len(sample1))

Total number of status updates for sample 1: 30000

In [7]:
print('Total number of status updates for sample 2:', len(sample2))

Total number of status updates for sample 2: 30000

## At least one hashtag

In [8]:
def find_hashtag(sample):
    total_hashtag = []
    for entity in sample.loc[:, 'entities']:
        list_hashtags = entity.get('hashtags')
        hashtag = []
        for elem in list_hashtags:
            h = elem.get('text')
            hashtag.append(h)
        total_hashtag.append(hashtag)
    return total_hashtag

In [9]:
sample1 = sample1.assign(hashtags=find_hashtag(sample1))
sample2 = sample2.assign(hashtags=find_hashtag(sample2))

In [10]:
def one_hashtag(sample):
    total = 0
    for list_h in sample.loc[:, 'hashtags']:
        if len(list_h) > 0:
            total += 1
    return total

In [11]:
one_hashtag1 = one_hashtag(sample1)
print('Number of Tweets in sample 1 that contain at least one hashtag:', one_hashtag1)
print('Percentage of Tweets in sample 1 that contain at least one hashtag:', one_hashtag1/len(sample1)*100, '%')

Number of Tweets in sample 1 that contain at least one hashtag: 7224
Percentage of Tweets in sample 1 that contain at least one hashtag: 24.08 %

In [12]:
one_hashtag2 = one_hashtag(sample2)
print('Number of Tweets in sample 2 that have at least one hashtag:', one_hashtag2)
print('Percentage of Tweets in sample 2 that have at least one hashtag:', one_hashtag2/len(sample2)*100, '%')

Number of Tweets in sample 2 that have at least one hashtag: 7220
Percentage of Tweets in sample 2 that have at least one hashtag: 24.066666666666666 %

## Two hashtags or more

In [13]:
def two_hashtag(sample):
    total = 0
    for list_h in sample.loc[:, 'hashtags']:
        if len(list_h) > 2:
            total += 1
    return total

In [14]:
two_hashtag1 = two_hashtag(sample1)
print('Number of Tweets in sample 1 that contain two or more hashtags:', two_hashtag1)
print('Percentage of Tweets in sample 1 that conatin two or more hashtags:', two_hashtag1/len(sample1)*100, '%')

Number of Tweets in sample 1 that contain two or more hashtags: 1885
Percentage of Tweets in sample 1 that conatin two or more hashtags: 6.283333333333334 %

In [15]:
two_hashtag2 = two_hashtag(sample2)
print('Number of Tweets in sample 2 that contain two or more hashtags:', two_hashtag2)
print('Percentage of Tweets in sample 2 that contain two or more hashtags:', two_hashtag2/len(sample2)*100, '%')

Number of Tweets in sample 2 that contain two or more hashtags: 1935
Percentage of Tweets in sample 2 that contain two or more hashtags: 6.45 %

## Media

In [16]:
def total_media(sample, numb):
    total_media = 0
    for entity in sample.loc[:, 'entities']:
        list_media = entity.get('media')
        if list_media is not None:
            total_media += 1
            
    
    print('Number of Tweets in sample', numb , 'that contain media:', total_media)
    print('Percentage of Tweets in sample', numb, 'that contain media:', total_media/len(sample)*100, '%')

In [17]:
total_media(sample1, 1)

Number of Tweets in sample 1 that contain media: 5138
Percentage of Tweets in sample 1 that contain media: 17.12666666666667 %

In [18]:
total_media(sample2, 2)

Number of Tweets in sample 2 that contain media: 5338
Percentage of Tweets in sample 2 that contain media: 17.793333333333333 %

## URLs

In [19]:
def total_url(sample, numb):
    total_url = 0
    for entity in sample.loc[:, 'entities']:
        list_urls = entity.get('urls')
        if len(list_urls) > 0:
            total_url += 1
            
    
    print('Number of Tweets in sample', numb , 'that contain URLs:', total_url)
    print('Percentage of Tweets in sample', numb, 'that contain URLs:', total_url/len(sample)*100, '%')

In [20]:
total_url(sample1, 1)

Number of Tweets in sample 1 that contain URLs: 6911
Percentage of Tweets in sample 1 that contain URLs: 23.036666666666665 %

In [21]:
total_url(sample2, 2)

Number of Tweets in sample 2 that contain URLs: 7033
Percentage of Tweets in sample 2 that contain URLs: 23.44333333333333 %

## 50 most frequent hashtags

In [22]:
hash1 = [val for sublist in find_hashtag(sample1) for val in sublist]
most_freq1 = pd.DataFrame(data=Counter(hash1).most_common(50), columns=['hashtag','occurences'])
most_freq1.index = np.arange(1, len(most_freq1)+1)
most_freq1

                 hashtag  occurences
1            switzerland          98
2         CanYouMakeIt16          81
3                    art          70
4            Switzerland          55
5                   quiz          53
6                 Hiring          53
7         noinonmolliamo          52
8          ODproroga2018          51
9                    Job          46
10                  Jobs          44
11                Geneva          44
12               NANTAIS          43
13  INCLingapSaTondo2016          41
14                   job          40
15              TheVoice          40
16           Controleurs          39
17             CareerArc          39
18                zurich          38
19                NANTES          37
20                  TPMP          37
21                   CFP          33
22         GreenUrbanism          33
23              Abstract          33
24              Deadline          33
25                  May1          33
26                  BATB          32
27                travel          31
28                  lake          31
29          bahnbilderde          28
30           photography          28
31           askbelieber          28
32                 Basel          27
33                Zurich          27
34              Veterans          26
35               TDR2016          26
36                  como          25
37                spring          25
38                  love          24
39                nature          24
40            TPMPAVegas          24
41           farmaciauno          23
42                sconti          23
43                 ggrmc          22
44            Radolfzell          22
45                 swiss          22
46                   LHC          21
47                hiring          21
48                 Sales          21
49                design          21
50             LesAnges8          21

In [23]:
hash2 = [val for sublist in find_hashtag(sample2) for val in sublist]
most_freq2 = pd.DataFrame(data=Counter(hash2).most_common(50), columns=['hashtag','occurences'])
most_freq2.index = np.arange(1, len(most_freq2)+1)
most_freq2

                 hashtag  occurences
1            switzerland          95
2         CanYouMakeIt16          92
3                   quiz          67
4         noinonmolliamo          62
5          ODproroga2018          61
6            Switzerland          59
7                    art          45
8                NANTAIS          44
9                 NANTES          43
10                Hiring          43
11           Controleurs          42
12                   Job          42
13                  TPMP          41
14                zurich          39
15              TheVoice          39
16                Zurich          38
17                   LHC          36
18           askbelieber          36
19  INCLingapSaTondo2016          36
20                  Jobs          34
21                Geneva          33
22                travel          32
23                geneva          31
24       ABSCBNFISHSTORY          30
25             CareerArc          29
26                 swiss          27
27                 LNews          27
28            TPMPAVegas          27
29               TDR2016          26
30                 Basel          26
31                   CFP          26
32         GreenUrbanism          26
33                Prince          25
34              srfarena          24
35                   job          24
36              Abstract          24
37              Deadline          24
38                  May1          24
39          bahnbilderde          23
40                  alps          21
41              lausanne          21
42                spring          21
43                  lake          21
44               Amici15          21
45             mountains          20
46            ciaodarwin          20
47                  love          20
48             landscape          20
49              Veterans          19
50         ABSCBNTWOFACE          19

## 50 most frequent hashtag pairs

In [24]:
def find_pair_hashtag(sample):
    pair_hashtag = []
    for list_hashtag in sample.loc[:, 'hashtags']:
        if len(list_hashtag) > 0:
            list_ = sorted(list_hashtag, key=str.lower)
            for i in range(0, len(list_)):
                for j in range(i+1, len(list_)):
                    pair_hashtag.append(tuple([list_[i], list_[j]]))
    return pair_hashtag

In [25]:
pair1 = find_pair_hashtag(sample1)
most_freq_pair1 = pd.DataFrame(data=Counter(pair1).most_common(50), columns=['hashtag pairs','occurences'])
most_freq_pair1.index = np.arange(1, len(most_freq_pair1)+1)
most_freq_pair1

                      hashtag pairs  occurences
1          (GarethBale, GarethBale)          64
2   (noinonmolliamo, ODproroga2018)          51
3                       (Job, Jobs)          42
4                   (Abstract, CFP)          33
5              (Abstract, Deadline)          33
6         (Abstract, GreenUrbanism)          33
7                  (Abstract, May1)          33
8                   (CFP, Deadline)          33
9              (CFP, GreenUrbanism)          33
10                      (CFP, May1)          33
11        (Deadline, GreenUrbanism)          33
12                 (Deadline, May1)          33
13            (GreenUrbanism, May1)          33
14              (CareerArc, Hiring)          30
15                    (Hiring, job)          28
16     (GarethBale11, GarethBale11)          28
17                    (Hiring, Job)          25
18                   (Hiring, Jobs)          25
19            (farmaciauno, sconti)          23
20                 (CareerArc, Job)          22
21                (CareerArc, Jobs)          22
22        (farmaciauno, promozioni)          21
23             (promozioni, sconti)          21
24             (donna, farmaciauno)          20
25              (donna, promozioni)          20
26                  (donna, sconti)          20
27                  (art, painting)          20
28                (bellezza, donna)          18
29          (bellezza, farmaciauno)          18
30           (bellezza, promozioni)          18
31               (bellezza, sconti)          18
32                  (art, iloveart)          18
33                 (CareerArc, job)          17
34               (Hiring, Veterans)          17
35          (Endomondo, endorphins)          17
36                   (art, fineart)          17
37                    (art, artwit)          16
38                  (Job, Veterans)          14
39                 (Jobs, Veterans)          14
40           (Radolfzell, Veterans)          14
41               (artwit, painting)          14
42              (fineart, iloveart)          14
43               (CareerArc, Sales)          13
44                  (Hiring, Sales)          13
45                      (DJ, DJANE)          12
46                    (hiring, Job)          12
47                     (1J1P, MPLF)          12
48             (Photo, Photography)          12
49                    (Geneva, Job)          12
50                     (Job, Sales)          12

In [26]:
pair2 = find_pair_hashtag(sample2)
most_freq_pair2 = pd.DataFrame(data=Counter(pair2).most_common(50), columns=['hashtag pairs','occurences'])
most_freq_pair2.index = np.arange(1, len(most_freq_pair2)+1)
most_freq_pair2

                      hashtag pairs  occurences
1   (noinonmolliamo, ODproroga2018)          61
2                       (Job, Jobs)          33
3          (GarethBale, GarethBale)          28
4                     (Hiring, Job)          26
5                    (Hiring, Jobs)          26
6              (CFP, GreenUrbanism)          26
7               (CareerArc, Hiring)          25
8                   (Abstract, CFP)          24
9              (Abstract, Deadline)          24
10        (Abstract, GreenUrbanism)          24
11                 (Abstract, May1)          24
12                  (CFP, Deadline)          24
13                      (CFP, May1)          24
14        (Deadline, GreenUrbanism)          24
15                 (Deadline, May1)          24
16            (GreenUrbanism, May1)          24
17                 (CareerArc, Job)          19
18                (CareerArc, Jobs)          19
19            (farmaciauno, sconti)          18
20                    (Hiring, job)          17
21        (farmaciauno, promozioni)          17
22             (promozioni, sconti)          17
23             (swiss, switzerland)          16
24             (donna, farmaciauno)          16
25              (donna, promozioni)          16
26                  (donna, sconti)          16
27               (Hiring, Veterans)          15
28            (switzerland, travel)          13
29             (Photo, Photography)          13
30                (bellezza, donna)          13
31          (bellezza, farmaciauno)          13
32           (bellezza, promozioni)          13
33               (bellezza, sconti)          13
34           (motormaniaci, sbandy)          12
35            (motormaniaci, webtv)          12
36                  (sbandy, webtv)          12
37                     (1J1P, MPLF)          12
38            (geneva, switzerland)          11
39            (switzerland, zurich)          11
40                    (art, artwit)          11
41                  (Job, Veterans)          10
42                (instamoto, moto)          10
43          (instamoto, motorcycle)          10
44        (instamoto, motormaniaci)          10
45              (instamoto, sbandy)          10
46               (instamoto, webtv)          10
47               (moto, motorcycle)          10
48             (moto, motormaniaci)          10
49                   (moto, sbandy)          10
50                    (moto, webtv)          10

## Discussion of results

I did not expect that the percentage of tweets that contain at least a hashatg to be so low, with not even 25%, as the hashatgs are the way for tweets to be noticed and to be part of a bigger "conversation".


As the two samples were taken at the same time, it can permit us to see if the subsamples given by Twitter when querying data are biaised or not. At first glance, we cannot claim that this biaised the data as the two samples have percentages that are very close for all the ones computed.

We can also see that there are some noise in the data, due to the fact that Switzerland has been approximated as a box, as we have hashtags like "NANTAIS" and "NANTES" that appear in the top 50 of sample1.

TO COMPLETE !!!!!!!!!!!!!

# Analysis of data from 2019

In [27]:
sample_2019 = pd.read_json('json/data.json', lines=True)

In [28]:
sample_2019 = sample_2019.iloc[0:3000]

## Total number of Tweets

In [29]:
print('Total number of status updates for sample of 2019:', len(sample_2019))

Total number of status updates for sample of 2019: 3000

## At least one hashtag

In [30]:
sample_2019 = sample_2019.assign(hashtags=find_hashtag(sample_2019))

In [31]:
one_hashtag_2019 = one_hashtag(sample_2019)
print('Number of Tweets in sample of 2019 that contain at least one hashtag:', one_hashtag_2019)
print('Percentage of Tweets in sample of 2019 that contain at least one hashtag:', one_hashtag_2019/len(sample_2019)*100, '%')

Number of Tweets in sample of 2019 that contain at least one hashtag: 579
Percentage of Tweets in sample of 2019 that contain at least one hashtag: 19.3 %

## Two hashtags or more

In [32]:
two_hashtag_2019 = two_hashtag(sample_2019)
print('Number of Tweets in sample of 2019 that contain two or more hashtags:', two_hashtag_2019)
print('Percentage of Tweets in sample of 2019 that conatin two or more hashtags:', two_hashtag_2019/len(sample_2019)*100, '%')

Number of Tweets in sample of 2019 that contain two or more hashtags: 217
Percentage of Tweets in sample of 2019 that conatin two or more hashtags: 7.233333333333333 %

## Media

In [33]:
total_media(sample_2019, 'of 2019')

Number of Tweets in sample of 2019 that contain media: 414
Percentage of Tweets in sample of 2019 that contain media: 13.8 %

## URLs

In [34]:
total_url(sample_2019, 'of 2019')

Number of Tweets in sample of 2019 that contain URLs: 1208
Percentage of Tweets in sample of 2019 that contain URLs: 40.266666666666666 %

## 50 most frequent hashtags

In [35]:
hash_2019 = [val for sublist in find_hashtag(sample_2019) for val in sublist]
most_freq_2019 = pd.DataFrame(data=Counter(hash_2019).most_common(50), columns=['hashtag','occurences'])
most_freq_2019.index = np.arange(1, len(most_freq_2019)+1)
most_freq_2019

             hashtag  occurences
1             winner          29
2              money          29
3               Tips          27
4            vintage          14
5        switzerland          12
6       fixedmatches          11
7          unterwegs           9
8        Switzerland           8
9               chat           7
10             perdu           7
11            ostern           7
12             Italy           5
13  NotreDameDeParis           5
14            france           5
15             italy           5
16          montreux           5
17      architecture           5
18        Karfreitag           5
19         NotreDame           5
20       photography           4
21            spring           4
22       happyeaster           4
23            easter           4
24               BTS           4
25          Yvelines           4
26            Poissy           4
27            zurich           4
28           schweiz           4
29            design           4
30       picoftheday           4
31        paques2019           3
32       HappyEaster           3
33            paques           3
34            Geneva           3
35            travel           3
36               ski           3
37          chamonix           3
38           fashion           3
39            Ostern           3
40        karfreitag           3
41             sunny           3
42        Eurovision           3
43               cdn           3
44           cdn2019           3
45   coupedesnations           3
46         since1921           3
47          Chamonix           3
48        ostern2019           3
49         mountains           3
50  PatrickSchnidrig           3

## 50 most frequent hashtag pairs

In [36]:
pair_2019 = find_pair_hashtag(sample_2019)
most_freq_pair_2019 = pd.DataFrame(data=Counter(pair_2019).most_common(50), columns=['hashtag pairs','occurences'])
most_freq_pair_2019.index = np.arange(1, len(most_freq_pair_2019)+1)
most_freq_pair_2019

                      hashtag pairs  occurences
1                   (money, winner)          29
2                     (money, Tips)          27
3                    (Tips, winner)          27
4             (fixedmatches, money)          11
5              (fixedmatches, Tips)          11
6            (fixedmatches, winner)          11
7                     (chat, perdu)           7
8                (Poissy, Yvelines)           4
9            (architecture, design)           4
10                   (cdn, cdn2019)           3
11           (cdn, coupedesnations)           3
12                  (cdn, montreux)           3
13                 (cdn, since1921)           3
14       (cdn2019, coupedesnations)           3
15              (cdn2019, montreux)           3
16             (cdn2019, since1921)           3
17      (coupedesnations, montreux)           3
18     (coupedesnations, since1921)           3
19            (montreux, since1921)           3
20             (ostern, ostern2019)           3
21  (PatrickSchnidrig, Switzerland)           3
22                (hair, instahair)           3
23                 (hair, menshair)           3
24                 (hair, skinfade)           3
25              (hair, streetstyle)           3
26         (hair, uniquehairdesign)           3
27            (instahair, menshair)           3
28            (instahair, skinfade)           3
29         (instahair, streetstyle)           3
30    (instahair, uniquehairdesign)           3
31             (menshair, skinfade)           3
32          (menshair, streetstyle)           3
33     (menshair, uniquehairdesign)           3
34          (skinfade, streetstyle)           3
35     (skinfade, uniquehairdesign)           3
36  (streetstyle, uniquehairdesign)           3
37                (italy, lakecomo)           2
38                  (italy, sicily)           2
39              (streaming, twitch)           2
40       (innovation, rolfcaviezel)           2
41            (montreux, polymanga)           2
42            (easter, happyeaster)           2
43                 (easter, ostern)           2
44       (froheostern, happyeaster)           2
45         (fashion, liechtenstein)           2
46                (fashion, london)           2
47                 (fashion, style)           2
48                 (fashion, sunny)           2
49                    (fashion, uk)           2
50                 (fashion, vaduz)           2

## Discussion of results

It is interesting to see that there is a evolution of how twitter is used in 2016 and 2019. The hashtags are less used as before as it passes from 24% to 19% of tweets that contain at least one hasthag. There is also a decrease in the percentage of tweets that contain medias. However, the most striking change is the percentage of tweets that contain URLs, as it passes from 23% to 40%. It shows that twitter is not used for sharing your opinions on subjects but more to share informations through the mean of URL. As we have seen in class that the information can be passed through intermediaries via either retweets or tweets of URLS and as the number of URLs shared in tweets raised, we can make the hypothesis that Twitter is now more a means of passing information than it was before.

TO COMPLETE !!!!!!!!!!!!!!!!

# Pairwise comparison

In [37]:
def common_hashtags(sample1, sample2, top):
    intersection = 0
    same_hashtags = []
    for i in range(1, top+1):
        for j in range(1, top+1):
            if sample1['hashtag'][i] == sample2['hashtag'][j]:
                same_hashtags.append(sample1['hashtag'][i])
                intersection += 1
    union = 2*top - intersection
    ratio = intersection / union
    print('Number of common hashtags in top', top, ':', intersection)
    print('Ratio of common hashtags in top ', top, ':', ratio)
    print('Common hashtags :', same_hashtags)

## Sample 1 vs. sample 2

### Common hashtags for top 20

In [38]:
common_hashtags(most_freq1, most_freq2, 20)

Number of common hashtags in top 20 : 17
Ratio of common hashtags in top  20 : 0.7391304347826086
Common hashtags : ['switzerland', 'CanYouMakeIt16', 'art', 'Switzerland', 'quiz', 'Hiring', 'noinonmolliamo', 'ODproroga2018', 'Job', 'Jobs', 'NANTAIS', 'INCLingapSaTondo2016', 'TheVoice', 'Controleurs', 'zurich', 'NANTES', 'TPMP']

### Common hashtags for top 50

In [39]:
common_hashtags(most_freq1, most_freq2, 50)

Number of common hashtags in top 50 : 38
Ratio of common hashtags in top  50 : 0.6129032258064516
Common hashtags : ['switzerland', 'CanYouMakeIt16', 'art', 'Switzerland', 'quiz', 'Hiring', 'noinonmolliamo', 'ODproroga2018', 'Job', 'Jobs', 'Geneva', 'NANTAIS', 'INCLingapSaTondo2016', 'job', 'TheVoice', 'Controleurs', 'CareerArc', 'zurich', 'NANTES', 'TPMP', 'CFP', 'GreenUrbanism', 'Abstract', 'Deadline', 'May1', 'travel', 'lake', 'bahnbilderde', 'askbelieber', 'Basel', 'Zurich', 'Veterans', 'TDR2016', 'spring', 'love', 'TPMPAVegas', 'swiss', 'LHC']

## Sample 1 vs. my sample

### Common hashtags for top 20

In [40]:
common_hashtags(most_freq1, most_freq_2019, 20)

Number of common hashtags in top 20 : 2
Ratio of common hashtags in top  20 : 0.05263157894736842
Common hashtags : ['switzerland', 'Switzerland']

### Common hashtags for top 50

In [41]:
common_hashtags(most_freq1, most_freq_2019, 50)

Number of common hashtags in top 50 : 8
Ratio of common hashtags in top  50 : 0.08695652173913043
Common hashtags : ['switzerland', 'Switzerland', 'Geneva', 'zurich', 'travel', 'photography', 'spring', 'design']

## Sample 2 vs. my sample

### Common hashtags for top 20

In [42]:
common_hashtags(most_freq2, most_freq_2019, 20)

Number of common hashtags in top 20 : 2
Ratio of common hashtags in top  20 : 0.05263157894736842
Common hashtags : ['switzerland', 'Switzerland']

### Common hashtags for top 50

In [43]:
common_hashtags(most_freq2, most_freq_2019, 50)

Number of common hashtags in top 50 : 7
Ratio of common hashtags in top  50 : 0.07526881720430108
Common hashtags : ['switzerland', 'Switzerland', 'zurich', 'Geneva', 'travel', 'spring', 'mountains']

## Discussion

As mentionned in the first part of the discussion, the idea of taking two samples at the same time can permit to see if the data collected via twitter is biaised or not. By looking only at the percentages computed in the first part, it did not seem that there was huge difference between sample 1 and 2. However, by looking at the common hashtags, we can see that the difference is bigger that it seems to be at first sight. For the top 20, it is still nice, as 17 hashtags are common, but we can see that the difference increases by looking at the top 50, as only 38 hashtags are common. This means that the 20 top hashtags are still well represented even if the sample given by Twitter represents only 1% of all the data. So if our interest is to look at the big trends present on Twitter, the sample given can be sufficient, but it our interest is to have a look on trends that are not that popular, our analysis can be really biaised by the data we can retrieve.

Now speaking about the difference betweeen samples of 2016 and 2019, we can see huge differences as only 2 hashatgs are the same in top 20, and the two hashtags are "Switzerland" and "switzerland". As we take the samples in order to have swiss tweets, it is not so surprising that these hashtags are still on top hashtags. We can think that the tweets containing theses hashatags are related to people travelling and visting Switzerland (as in the top 50, common hashatgs between 2016 and 2019 are for example "travel" (sample1 and sample2) and "photography"(sample1)), and this does not change through years. People continue to visit Switzerland and taking pictures, and sharing them on Twitter. This is why we can also find "Geneva" and "zurich" as they are the biggest cities of Switzerlandm and then ones of the most visited cities of the country. It is not really surprising that only few tweets are common through the years, as the hashtags are used to shared immediate thoughts about a subject, most of the time subjects that are related to the actuality, and so even if the period of the year is the same, the actuality is not the same, and so very few tweets are common. The only common tweet that is related to the period of the year is the hashtag "spring", and I think that it is because it is not linked with actuality that we can find it again 3 years later.